name: astra_admin_app
description: An admin app for Astra

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  auto_route: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: 4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_lints: ^1.0.0
  flutter_svg: ^0.22.0
  freezed_annotation: ^1.0.0
  get_it: ^7.2.0
  highlighter_coachmark: ^0.0.3
  http: ^0.13.4
  image_picker: ^0.8.4+4
  injectable: ^1.5.0
  json_annotation: ^4.4.0
  keyboard_dismisser: ^2.0.0
  mask_text_input_formatter: ^2.0.0
  path_provider: ^2.0.7
  pin_code_fields: ^7.3.0
  sembast: ^3.1.1
  shared_preferences: ^2.0.9

dev_dependencies:
  auto_route_generator: ^3.1.0
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^1.0.2
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.1
  lint: ^1.7.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
    - assets/